#!/usr/bin/env python

def contar_letras(palabra):
	cuentas={}
	for letra in palabra:
		if letra not in cuentas:
			cuentas[letra] = 0
		cuentas[letra] = cuentas[letra] + 1
	return cuentas

if __name__ == '__main__':

	palabra=input("Escribe una palabra lo mas larga posible:\n")

	print(contar_letras(palabra))